version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: uvicorn api:app --host 0.0.0.0
    ports:
      - 8000:8000
    working_dir: /app/src

  discord:
    build:
      context: .
      dockerfile: Dockerfile-discord
    command: python discord_bot.py
    ports:
      - 9090:8080
    working_dir: /app/src

  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    env_file: env/db.env
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: